=== NodeL2/NodeL2/data/Skills/.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "selfId": {
                "type": "integer"
            },
            "name": {
                "type": "string"
            },
            "passive": {
                "type": "boolean"
            },
            "hitTime": {
                "type": "integer"
            },
            "reuseTime": {
                "type": "integer"
            }
        },
        "required": [
            "selfId",
            "name",
            "passive",
            "hitTime",
            "reuseTime"
        ]
    }
}

=== NodeL2/NodeL2/data/Skills/skills.json
[{
    "selfId": 118, "name": "Magician's Movement", "passive": true, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 134, "name": "Toughness", "passive": true, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 163, "name": "Spellcraft", "passive": true, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 194, "name": "Lucky", "passive": true, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 214, "name": "Mana Recovery", "passive": true, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 1001, "name": "Soul Cry", "passive": false, "hitTime": 0, "reuseTime": 0
},{
    "selfId": 1177, "name": "Wind Strike", "passive": false, "hitTime": 4000, "reuseTime": 6000
},{
    "selfId": 1216, "name": "Self Heal", "passive": false, "hitTime": 5000, "reuseTime": 10000
}]
