=== NodeL2/NodeL2/data/Templates/.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "classId": {
                "type": "integer"
            },
            "template": {
                "type": "object",
                "properties": {
                    "class": {
                        "type": "string"
                    },
                    "race": {
                        "type": "integer"
                    },
                    "crafter": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "class",
                    "race",
                    "crafter"
                ]
            },
            "base": {
                "type": "object",
                "properties": {
                    "str": {
                        "type": "integer"
                    },
                    "dex": {
                        "type": "integer"
                    },
                    "con": {
                        "type": "integer"
                    },
                    "int": {
                        "type": "integer"
                    },
                    "wit": {
                        "type": "integer"
                    },
                    "men": {
                        "type": "integer"
                    }
                },
                "required": [
                    "str",
                    "dex",
                    "con",
                    "int",
                    "wit",
                    "men"
                ]
            },
            "stats": {
                "type": "object",
                "properties": {
                    "pAtk": {
                        "type": "integer"
                    },
                    "mAtk": {
                        "type": "integer"
                    },
                    "pDef": {
                        "type": "integer"
                    },
                    "mDef": {
                        "type": "integer"
                    },
                    "crit": {
                        "type": "integer"
                    },
                    "atkSpd": {
                        "type": "integer"
                    },
                    "castSpd": {
                        "type": "integer"
                    }
                },
                "required": [
                    "pAtk",
                    "mAtk",
                    "pDef",
                    "mDef",
                    "crit",
                    "atkSpd",
                    "castSpd"
                ]
            },
            "vitals": {
                "type": "object",
                "properties": {
                    "maxHp": {
                        "type": "integer"
                    },
                    "maxMp": {
                        "type": "integer"
                    },
                    "maxLoad": {
                        "type": "integer"
                    }
                },
                "required": [
                    "maxHp",
                    "maxMp",
                    "maxLoad"
                ]
            },
            "speed": {
                "type": "object",
                "properties": {
                    "walk": {
                        "type": "integer"
                    },
                    "run": {
                        "type": "integer"
                    },
                    "swim": {
                        "type": "integer"
                    }
                },
                "required": [
                    "walk",
                    "run",
                    "swim"
                ]
            },
            "collision": {
                "type": "object",
                "properties": {
                    "radius": {
                        "type": "number"
                    },
                    "size": {
                        "type": "number"
                    }
                },
                "required": [
                    "radius",
                    "size"
                ]
            }
        },
        "required": [
            "classId",
            "template",
            "base",
            "stats",
            "vitals",
            "speed",
            "collision"
        ]
    }
}

=== NodeL2/NodeL2/data/Templates/templates.json
[{
    "classId": 0,
    "template": { "class": "Human Fighter", "race": 0, "crafter": false },
    "base": { "str": 40, "dex": 30, "con": 43, "int": 21, "wit": 11, "men": 25 },
    "stats": { "pAtk": 4, "mAtk": 6, "pDef": 80, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 80, "maxMp": 30, "maxLoad": 81900 },
    "speed": { "walk": 80, "run": 115, "swim": 50 },
    "collision": { "radius": 9, "size": 23 }
},{
    "classId": 10,
    "template": { "class": "Human Mystic", "race": 0, "crafter": false },
    "base": { "str": 22, "dex": 21, "con": 27, "int": 41, "wit": 20, "men": 39 },
    "stats": { "pAtk": 3, "mAtk": 6, "pDef": 54, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 101, "maxMp": 40, "maxLoad": 62500 },
    "speed": { "walk": 78, "run": 120, "swim": 50 },
    "collision": { "radius": 7.5, "size": 22.8 }
},{
    "classId": 18,
    "template": { "class": "Elven Fighter", "race": 1, "crafter": false },
    "base": { "str": 36, "dex": 35, "con": 36, "int": 23, "wit": 14, "men": 26 },
    "stats": { "pAtk": 4, "mAtk": 6, "pDef": 80, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 89, "maxMp": 30, "maxLoad": 73840 },
    "speed": { "walk": 90, "run": 125, "swim": 50 },
    "collision": { "radius": 7.5, "size": 24 }
},{
    "classId": 25,
    "template": { "class": "Elven Mystic", "race": 1, "crafter": false },
    "base": { "str": 21, "dex": 24, "con": 25, "int": 37, "wit": 23, "men": 40 },
    "stats": { "pAtk": 3, "mAtk": 6, "pDef": 54, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 104, "maxMp": 40, "maxLoad": 62400 },
    "speed": { "walk": 85, "run": 122, "swim": 50 },
    "collision": { "radius": 7.5, "size": 24 }
},{
    "classId": 31,
    "template": { "class": "Dark Elven Fighter", "race": 2, "crafter": false },
    "base": { "str": 41, "dex": 34, "con": 32, "int": 25, "wit": 12, "men": 26 },
    "stats": { "pAtk": 4, "mAtk": 6, "pDef": 80, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 94, "maxMp": 30, "maxLoad": 69000 },
    "speed": { "walk": 85, "run": 122, "swim": 50 },
    "collision": { "radius": 7.5, "size": 24 }
},{
    "classId": 38,
    "template": { "class": "Dark Elven Mystic", "race": 2, "crafter": false },
    "base": { "str": 23, "dex": 23, "con": 24, "int": 44, "wit": 19, "men": 37 },
    "stats": { "pAtk": 3, "mAtk": 6, "pDef": 54, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 106, "maxMp": 40, "maxLoad": 61000 },
    "speed": { "walk": 85, "run": 122, "swim": 50 },
    "collision": { "radius": 7.5, "size": 24 }
},{
    "classId": 44,
    "template": { "class": "Orc Fighter", "race": 3, "crafter": false },
    "base": { "str": 40, "dex": 26, "con": 47, "int": 18, "wit": 12, "men": 27 },
    "stats": { "pAtk": 4, "mAtk": 6, "pDef": 80, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 80, "maxMp": 30, "maxLoad": 87000 },
    "speed": { "walk": 70, "run": 117, "swim": 50 },
    "collision": { "radius": 11, "size": 28 }
},{
    "classId": 49,
    "template": { "class": "Orc Mystic", "race": 3, "crafter": false },
    "base": { "str": 27, "dex": 24, "con": 31, "int": 31, "wit": 15, "men": 42 },
    "stats": { "pAtk": 3, "mAtk": 6, "pDef": 54, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 95, "maxMp": 40, "maxLoad": 68000 },
    "speed": { "walk": 70, "run": 121, "swim": 50 },
    "collision": { "radius": 7, "size": 27.5 }
},{
    "classId": 53,
    "template": { "class": "Dwarven Fighter", "race": 4, "crafter": true },
    "base": { "str": 39, "dex": 29, "con": 45, "int": 20, "wit": 10, "men": 27 },
    "stats": { "pAtk": 4, "mAtk": 6, "pDef": 80, "mDef": 41, "crit": 40, "atkSpd": 300, "castSpd": 333 },
    "vitals": { "maxHp": 80, "maxMp": 30, "maxLoad": 83000 },
    "speed": { "walk": 80, "run": 115, "swim": 50 },
    "collision": { "radius": 9, "size": 18 }
}]
